### ISSUE TITLE
Creating an instance is "MFRC522" or "MFRC522_I2C"?

### ISSUE THREAD

**Issue by Bendikos** [kkloesener/MFRC522_I2C#1]
![418bfdc506ccf7410a048a5a4e9f80b](https://github.com/kkloesener/MFRC522_I2C/assets/102461738/b11e4521-602e-47cf-8db2-7da49abd0bd2)

**Comment by kkloesener** [comment]
the example is wrong - it should be MFRC522_I2C
I will correct that in the example. Thank you for opening this issue

**Comment by kkloesener** [comment]
This has been fixed with latest commit
